sudo: false
language: python

matrix:
  include:
    - os: linux
      dist: xenial
      env: CC=gcc
      python: 3.6
    - os: linux
      dist: xenial
      env: CC=clang
      python: 3.6

install:
  - export NINJA_LATEST=$(curl -s https://api.github.com/repos/ninja-build/ninja/releases/latest | grep browser_download_url | cut -d '"' -f 4 | grep ninja-linux.zip)
  - wget "$NINJA_LATEST"
  - unzip -q ninja-linux.zip -d ninja
  - export PATH="$PWD/ninja:$PATH"
  - pip install meson
  - echo $PATH
  - ls ninja
  - ninja --version

script:
  - meson build
  - ninja -C build
  - ./build/euler-c check --timeout 100

addons:
  apt:
    packages:
    - libjansson-dev
